/**
 * Architecture constants, taken from AMD64 Architecture Programmer's manual
 */


export enum RegisterFamily {
    rAX, rBX, rCX, rDX, rSI, rDI, rBP, rSP,
    r8, r9, r10, r11, r12, r13, r14, r15,
}

// General purpose 64-bit registers
export enum Register64 {
    RAX, RBX, RCX, RDX, RSI, RDI, RBP, RSP,
    R8, R9, R10, R11, R12, R13, R14, R15,
}

export enum Register {
    RAX, RBX, RCX, RDX, RSI, RDI, RBP, RSP,
    R8, R9, R10, R11, R12, R13, R14, R15,
    EAX, EBX, ECX, EDX, ESI, EDI, EBP, ESP, R8D,
    R9D, R10D, R11D, R12D, R13D, R14D, R15D,
    AX, BX, CX, DX, SI, DI, BP, SP, R8W,
    R9W, R10W, R11W, R12W, R13W, R14W, R15W,
    AH, AL, BH, BL, CH, CL, DH, DL, SIL, DIL,
    BPL, SPL, R8B, R9B, R10B, R11B, R12B, R13B, R14B, R15B,
}

export const registerReverseMap: { [key in Register]: Register64 } = {
    [Register.RAX]: Register64.RAX,
    [Register.RBX]: Register64.RBX,
    [Register.RCX]: Register64.RCX,
    [Register.RDX]: Register64.RDX,
    [Register.RSI]: Register64.RSI,
    [Register.RDI]: Register64.RDI,
    [Register.RBP]: Register64.RBP,
    [Register.RSP]: Register64.RSP,
    [Register.R8]: Register64.R8,
    [Register.R9]: Register64.R9,
    [Register.R10]: Register64.R10,
    [Register.R11]: Register64.R11,
    [Register.R12]: Register64.R12,
    [Register.R13]: Register64.R13,
    [Register.R14]: Register64.R14,
    [Register.R15]: Register64.R15,
    [Register.EAX]: Register64.RAX,
    [Register.EBX]: Register64.RBX,
    [Register.ECX]: Register64.RCX,
    [Register.EDX]: Register64.RDX,
    [Register.ESI]: Register64.RSI,
    [Register.EDI]: Register64.RDI,
    [Register.EBP]: Register64.RBP,
    [Register.ESP]: Register64.RSP,
    [Register.R8D]: Register64.R8,
    [Register.R9D]: Register64.R9,
    [Register.R10D]: Register64.R10,
    [Register.R11D]: Register64.R11,
    [Register.R12D]: Register64.R12,
    [Register.R13D]: Register64.R13,
    [Register.R14D]: Register64.R14,
    [Register.R15D]: Register64.R15,
    [Register.AX]: Register64.RAX,
    [Register.BX]: Register64.RBX,
    [Register.CX]: Register64.RCX,
    [Register.DX]: Register64.RDX,
    [Register.SI]: Register64.RSI,
    [Register.DI]: Register64.RDI,
    [Register.BP]: Register64.RBP,
    [Register.SP]: Register64.RSP,
    [Register.R8W]: Register64.R8,
    [Register.R9W]: Register64.R9,
    [Register.R10W]: Register64.R10,
    [Register.R11W]: Register64.R11,
    [Register.R12W]: Register64.R12,
    [Register.R13W]: Register64.R13,
    [Register.R14W]: Register64.R14,
    [Register.R15W]: Register64.R15,
    [Register.AH]: Register64.RAX,
    [Register.AL]: Register64.RAX,
    [Register.BH]: Register64.RBX,
    [Register.BL]: Register64.RBX,
    [Register.CH]: Register64.RCX,
    [Register.CL]: Register64.RCX,
    [Register.DH]: Register64.RDX,
    [Register.DL]: Register64.RDX,
    [Register.SIL]: Register64.RSI,
    [Register.DIL]: Register64.RDI,
    [Register.BPL]: Register64.RBP,
    [Register.SPL]: Register64.RSP,
    [Register.R8B]: Register64.R8,
    [Register.R9B]: Register64.R9,
    [Register.R10B]: Register64.R10,
    [Register.R11B]: Register64.R11,
    [Register.R12B]: Register64.R12,
    [Register.R13B]: Register64.R13,
    [Register.R14B]: Register64.R14,
    [Register.R15B]: Register64.R15,
}

export const registerOffset: { [key in Register]: number } = {
    [Register.RAX]: 0,
    [Register.RBX]: 0,
    [Register.RCX]: 0,
    [Register.RDX]: 0,
    [Register.RSI]: 0,
    [Register.RDI]: 0,
    [Register.RBP]: 0,
    [Register.RSP]: 0,
    [Register.R8]: 0,
    [Register.R9]: 0,
    [Register.R10]: 0,
    [Register.R11]: 0,
    [Register.R12]: 0,
    [Register.R13]: 0,
    [Register.R14]: 0,
    [Register.R15]: 0,
    [Register.EAX]: 4,
    [Register.EBX]: 4,
    [Register.ECX]: 4,
    [Register.EDX]: 4,
    [Register.ESI]: 4,
    [Register.EDI]: 4,
    [Register.EBP]: 4,
    [Register.ESP]: 4,
    [Register.R8D]: 4,
    [Register.R9D]: 4,
    [Register.R10D]: 4,
    [Register.R11D]: 4,
    [Register.R12D]: 4,
    [Register.R13D]: 4,
    [Register.R14D]: 4,
    [Register.R15D]: 4,
    [Register.AX]: 6,
    [Register.BX]: 6,
    [Register.CX]: 6,
    [Register.DX]: 6,
    [Register.SI]: 6,
    [Register.DI]: 6,
    [Register.BP]: 6,
    [Register.SP]: 6,
    [Register.R8W]: 6,
    [Register.R9W]: 6,
    [Register.R10W]: 6,
    [Register.R11W]: 6,
    [Register.R12W]: 6,
    [Register.R13W]: 6,
    [Register.R14W]: 6,
    [Register.R15W]: 6,
    [Register.AH]: 6,
    [Register.AL]: 7,
    [Register.BH]: 6,
    [Register.BL]: 7,
    [Register.CH]: 6,
    [Register.CL]: 7,
    [Register.DH]: 6,
    [Register.DL]: 7,
    [Register.SIL]: 7,
    [Register.DIL]: 7,
    [Register.BPL]: 7,
    [Register.SPL]: 7,
    [Register.R8B]: 7,
    [Register.R9B]: 7,
    [Register.R10B]: 7,
    [Register.R11B]: 7,
    [Register.R12B]: 7,
    [Register.R13B]: 7,
    [Register.R14B]: 7,
    [Register.R15B]: 7,
}

export const registerWidth: { [key in Register]?: number } = {
    [Register.RAX]: 8,
    [Register.RBX]: 8,
    [Register.RCX]: 8,
    [Register.RDX]: 8,
    [Register.RSI]: 8,
    [Register.RDI]: 8,
    [Register.RBP]: 8,
    [Register.RSP]: 8,
    [Register.R8]: 8,
    [Register.R9]: 8,
    [Register.R10]: 8,
    [Register.R11]: 8,
    [Register.R12]: 8,
    [Register.R13]: 8,
    [Register.R14]: 8,
    [Register.R15]: 8,
    [Register.EAX]: 4,
    [Register.EBX]: 4,
    [Register.ECX]: 4,
    [Register.EDX]: 4,
    [Register.ESI]: 4,
    [Register.EDI]: 4,
    [Register.EBP]: 4,
    [Register.ESP]: 4,
    [Register.R8D]: 4,
    [Register.R9D]: 4,
    [Register.R10D]: 4,
    [Register.R11D]: 4,
    [Register.R12D]: 4,
    [Register.R13D]: 4,
    [Register.R14D]: 4,
    [Register.R15D]: 4,
    [Register.AX]: 2,
    [Register.BX]: 2,
    [Register.CX]: 2,
    [Register.DX]: 2,
    [Register.SI]: 2,
    [Register.DI]: 2,
    [Register.BP]: 2,
    [Register.SP]: 2,
    [Register.R8W]: 2,
    [Register.R9W]: 2,
    [Register.R10W]: 2,
    [Register.R11W]: 2,
    [Register.R12W]: 2,
    [Register.R13W]: 2,
    [Register.R14W]: 2,
    [Register.R15W]: 2,
    [Register.AH]: 1,
    [Register.AL]: 1,
    [Register.BH]: 1,
    [Register.BL]: 1,
    [Register.CH]: 1,
    [Register.CL]: 1,
    [Register.DH]: 1,
    [Register.DL]: 1,
    [Register.SIL]: 1,
    [Register.DIL]: 1,
    [Register.BPL]: 1,
    [Register.SPL]: 1,
    [Register.R8B]: 1,
    [Register.R9B]: 1,
    [Register.R10B]: 1,
    [Register.R11B]: 1,
    [Register.R12B]: 1,
    [Register.R13B]: 1,
    [Register.R14B]: 1,
    [Register.R15B]: 1,
}
